Proyecto_Final/Lo_Visto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('user/<str:llave>', views.pagina_usuario),
    path('informacion/', views.pagina_informacion),
    path('aportaciones/', views.aportaciones),
    path('<str:llave>',views.recurso),
]

Proyecto_Final/Proyecto_Final/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from django.contrib.auth.views import LogoutView as logout

urlpatterns = [
    path('Lo_Visto/', include('Lo_Visto.urls')),
    path('admin/', admin.site.urls),
    path('login/', login.as_view()),
    path('logout/', logout.as_view())
]

Proyecto_Final/Lo_Visto/models.py
from django.db import models

# Create your models here.

class Pages(models.Model):

    PAGES=[
        ('AE', 'aemet'),
        ('YT', 'youtube'),
        ('WK', 'wikipedia'),
        ('RD', 'reddit'),
        ('NR', 'other'),
    ]

    page = models.CharField(max_length=2, choices=PAGES)
    def __str__(self):
       return str(self.id) + ":" + self.page

class Contenido(models.Model):

    clave = models.CharField(max_length=64)
    usuario = models.TextField()
    valor = models.TextField()
    page = models.ManyToManyField(Pages)
    nvotos_pos = models.IntegerField()
    nvotos_neg = models.IntegerField()
    NumComent = models.IntegerField()
    fecha = models.DateTimeField('published')

    def __str__(self):
       return self.clave+":"+self.valor

class Comentario(models.Model):

    contenido = models.ForeignKey(Contenido,on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    valor = models.TextField()
    usuario = models.TextField()
    fecha = models.DateTimeField('published')
    link_imagen = models.TextField(default="No url")

    def __str__(self):
        return self.titulo + ":" + self.valor

class Voto(models.Model):
    contenido = models.ForeignKey(Contenido,on_delete=models.CASCADE)
    valor = models.TextField()
    usuario = models.TextField()

    def __str__(self):
       return str(self.contenido)+":"+self.usuario

Proyecto_Final/templates/Cosas Pagina/AEMET.html
{% extends 'Cosas Pagina/recurso.html' %}

{%block aportacion%}

    <div class="aemet">
        <p>{{titulo}}</p>
        <ul>
            <li> Dia:{{fecha12}}.</li>
            <li> Temperatura 12-18h: {{temp12}}</li>
            <li> Temperatura mínima y máxima (°C):{{maxymin}}</li>
            <li> Probabilidad de precipitación:{{precipitacion}}</li>
        </ul>
        <p>© AEMET. Autorizado el uso de la información y su reproducción citando a AEMET como autora de la misma.
        <br>
            <a href={{contenido.valor}}>Página original en AEMET</a></p>
    </div>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/aportaciones.html
{% extends 'Cosas Pagina/schema.html' %}
{%block cuerpo%}
    {%if contenido_list%}
        <h1>
            En esta seccion podremos encontrar todas las<br>
            aportaciones realizadas en la pagina de Lo_Visto.<br>
            Estas apareceran ordenadas apareciendo primero las<br>
            aportaciones realizadas mas recientemente.<br>
        </h1>
        <table style="width:auto" align="center">

               {%for contenido in contenido_list%}

                <tr>
                   <td>
                       <a href="{{contenido.clave}}">{{contenido.clave}}</a>

                   </td>
                </tr>
            {%endfor%}

       </table>

    {%else%}
        <p>No tenemos contenidos que mostrar</p>
    {%endif%}

{% endblock %}

{%block lateral%}

<br><br>

{% endblock %}

Proyecto_Final/templates/Cosas Pagina/contenido_no_encontrado.html
{% extends 'Cosas Pagina/schema.html' %}
{%block cuerpo%}

    {%  if request.user.is_authenticated%}
            Este contenido no existe, lo puedes añadir
        <table style="width:auto" align="center">
            <form action="" method ="POST">
                {% csrf_token %}
               <tr>
                    <td><br>Cuerpo: </td>
                     <td><input type="text" name="valor"></td>
               </tr>
                <tr>
                     <td><br/><input class="boton_personalizado" type="submit" name="action" value="Enviar contenido"></td>
                </tr>
            </form>
         </table>

    {% else %}
         <p>Para poder añadir un comentario necesitas estar autenticado<p/>
    {%endif%}

{%endblock%}

{%block lateral%}

<form action="" method ="POST">
            {% csrf_token %}
        <br/><input class="boton_personalizado"type="submit" name="action" value="gohome">
    </form>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/elpais.html
{% extends 'Cosas Pagina/recurso.html' %}

{%block aportacion%}

    <div class="reddit">
        <p>Noticia: {{titulo}}</p>
        <img src="{{ imagen }}" align="center" width="300">
    <br>
        <p>{{text}}</p>
        <p><a href="https://as.com/"></a></p>
    </div>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <style>

        width: 100%;
        h1{font-size:25px;font-style: oblique;}
        p{font-size:20px;font-style: oblique;}
        body{ background-color: #FBF0FF}

        .header {
          width:98%;
          height:30%;
          overflow: hidden;
          background-color: #C6ACCF;
          padding: 10px 10px;
          border-radius: 10px;
          border-color: #58465F;
          border-style: groove;
          font-size:50px;
          text-align: center;
          font-style: italic;
          color: white;
          margin-left: 1%;

        }
        .session{
            margin-right: 20px;
            width:98%%;
            height:20%;
            overflow: hidden;
            color: white;
            padding: 10px 10px;
            border-radius: 8px;
            border-style: groove;
            background-color: #C6ACCF;
            border-color: #58465F;
            text-align: center;
            font-size:20px;
            padding: 10px;
            margin-left: 1.5%;
            margin-top:5px;
        }
        #session-left{float: left; margin-left: 10%}
        #session-right{float: right; margin-right: 10%}
        #boton_paginappal{justify-content: center;}
        #nombre_usuario{width: 30%; justify-content: center; margin-left: 30%;}
        #idformnoticias{width: 90%;margin-left: 5%; }
        .inputnoticias{width: 100%; }
        main{
            margin-right: 20px;
            width:98%;
            height:20%;
            overflow: hidden;
            color: white;
            padding: 10px 10px;
            border-radius: 8px;
            border-style: groove;
            background-color: #C6ACCF;
            border-color: #58465F;
            margin-top:5px;
            text-align: center;
            font-size:20px;
            margin: 1%;
        }
        aside {
          width: 40%;
          height: 50%;
          text-align: left;
          border: #1245a3 3px solid  ;
          border-radius: 18px;
          padding-top: 20px;
          padding-right: 0px;
          padding-bottom: 40px;
          padding-left: 40px
          margin-right: 20px;
          overflow: auto;
          color: white;
          padding: 10px 10px;
            border-style: groove;
            background-color: #C6ACCF;
            border-color: #58465F;
            margin-top:5px;
          font-size:20px;
            margin-left: 30%;
        }
        .footer{
            clear:both;
            margin: 0px;
            width:100%;
            text-align: right;
            color: black;
                        border-style: groove;
            background-color: #C6ACCF;
            border-color: #58465F;
            margin-top:5px;
            font-size:15px;
            height: 10%;
            text-align: center;
        }
        .boton_log{
            text-decoration: none;
            padding: 2px;
            font-weight: 67;
            font-size: 20px;
            background-color: #FBF0FF;
            border-radius: 8px;
            border: black 2px solid ;
            margin:5px;
        }
        .boton_personalizado{
            text-decoration: none;
            padding: 10px;
            font-weight: 600;
            font-size: 17px;
            color: #ffffff;
            background-color: #58465F;
            border-radius: 8px;
             border-style: groove;
            border: #blue 2px solid #;
            width: 40%;
            margin-left: 25%;
            margin-top:10px;
        }
        table{
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 100%;
          border: blue 6px solid #;
        }
        td, th {
          border: 1px solid #dddddd;
          text-align: left;
          padding: 2px;
        }

        tablacontent{
         width: 100%;
        }
        img{
        display:block;
        margin:auto;
        }


     </style>
</head>
<body>

    {% extends 'Cosas Pagina/schema.html' %}
{%block cuerpo%}

 {{request.user.username}}, Bienvenido, esta es tu pagina personal.<br>
    Solo tu tienes acceso a esta pagina, y en ella vas <br>
    a encontrar todas tus publicaciones, comentarios y votos.

{%if contenido_list%}
<br><br>
<p>Publicaciones de {{request.user.username}}</p>
 {%for contenido in contenido_list%}
             {% ifequal contenido.usuario request.user.username %}
 <br>
                <table style="width:auto" align="center">
                    <th><a href="/{{contenido.clave}}">{{contenido.clave}}</a></th>
                    <tr>
                        <td>el valor de la clave es:</td>
                        <td>{{ contenido.valor }}</td>
                    </tr>
                    <tr>
                       <td>votos positivos: </td>
                        <td>{{ contenido.nvotos_pos }}</td>
                    </tr>
                    <tr>
                        <td>votos negativos: </td>
                        <td>{{ contenido.nvotos_neg }}</td>
                    </tr>
                    <tr>
                        <td>fecha de publicacion: </td>
                         <td>{{ contenido.fecha }}</td>
                    </tr>
                    <tr>
                        <td>numero de comentarios: </td>
                        <td>{{ contenido.NumComent }}</td>
                    </tr>
                 </table>
             {%endifequal%}
{%endfor%}
<br><br>

{%else%}
        <p>No tenemos contenidos que mostrar</p>
{%endif%}
<p>Comentarios de {{request.user.username}}</p>
        {%for comentario in comment_list%}
            {% ifequal comentario.usuario request.user.username %}
                <br>
                    <table style="width:auto" align="center">
                                <tr>
                                    <td><b>Titulo:<b/><td>
                                    <td>{{comentario.titulo }}</td>
                                </tr>
                                <tr>
                                    <td><b>Cuerpo:<b/><td>
                                    <td> {{comentario.valor }}</td>
                                </tr>
                        <tr>
                                    <td><b>Usuario:<b/><td>
                                    <td> {{comentario.usuario }}</td>
                                </tr>
                                <tr>
                                    <td><b>Fecha:<b/><td>
                                    <td>{{ comentario.fecha }}</td>
                                </tr>
                    </table>

            {%endifequal%}
        {%endfor%}

 <br>

<p>Votos de {{request.user.username}}</p>
<br>

{%for votoaux in vote_list%}
            {% ifequal votoaux.usuario request.user.username %}
                <table style="width:auto" align="center">
                    <tr>
                        <td><b>Valor del voto :<b/></td>
                        <td>{{ votoaux.valor }}</td>
                    </tr>
                    <tr>
                        <td><b>tema votado:<b/></td>
                         <td>{{ votoaux.contenido }}</td>
                    </tr>

                </table>
                <br> <br> <br>
            {%endifequal%}
<br>
{%endfor%}


{% endblock %}
</body>
</html>

Proyecto_Final/templates/Cosas Pagina/informacion.html
{% extends 'Cosas Pagina/schema.html' %}
{%block cuerpo%}
<p>
  En esta pagina se encuentra la informacion de la practica y su autoria.<br>

<p/>
<p>
  Soy Jorge López-Cano, el autor de esta aplicaion llamada LoVisto.<br>
  Para la realizacion de la practica que se esta observando, se ha utilizado python a traves de django.<br>
  El funcionamiento de la practica consiste en, realizar aportaciones en la pagina principal, que deben ser<br>
  urls de videos, fotos o noticias, las cuales son compartidas con las que han realizado el resto de usuarios.<br>
  De algunos recursos especificos se pòdran extraer el titulo, texto y una imagen, como es de reddit o de la pagina<br>
  de El Pais. <br>
  Tambien se podran realizar comentarios a las aportaciones subidas desde la propia pagina del recurso.<br>
  Para el desarrollo se ha usado herramientas externas como beautiful soup y urlopen.<br>

<p/>

<p/>
<p>

</p>
 <p>
   Contenido adicional de la practica:
   <br>Se ha implementado un favicon de la pagina, el cual se encuentra en la carpeta static.
   <br>Se han añadido para implementar una imagen en los comentarios a traves de su url.
   <br>Se han añadido dos recursos mas de dos paginas que no se incluian: el pais y el mundo today.
<p/>
{% endblock %}

Proyecto_Final/templates/Cosas Pagina/mundotoday.html
{% extends 'Cosas Pagina/recurso.html' %}

{%block aportacion%}

    <div class="reddit">
        <p>Noticia: {{titulo}}</p>
        <img src="{{ imagen }}" align="center" width="300">
    <br>
        <p>{{text}}</p>
        <p><a href="https://www.elmundotoday.com/"></a></p>
    </div>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/paginappal.html
{% extends 'Cosas Pagina/schema.html' %}
{%block cuerpo%}
    {%if contenido_list_10_publicaciones%}
    <h1>

        Esta es la pagina principal de Lo_Visto, en ella podras subir nuevo material y otras
        personas podran darle me gusta y opinar sobre el.

    </h1>
           {%for contenido in contenido_list_10_publicaciones%}
<br><br>
                      <table style="width:auto" align="rigth">
                        <th><a href="{{contenido.valor}}">{{contenido.clave}}</a></th>
                        <tr>
                            <td>el valor de la clave es:</td>
                            <td>{{ contenido.valor }}</td>
                        </tr>
                        <tr>
                           <td>votos positivos: </td>
                            <td>{{ contenido.nvotos_pos }}</td>
                        </tr>
                        <tr>
                            <td>votos negativos: </td>
                            <td>{{ contenido.nvotos_neg }}</td>
                        </tr>
                        <tr>
                            <td>fecha de publicacion: </td>
                             <td>{{ contenido.fecha }}</td>
                        </tr>
                          <tr>
                            <td>Publicado por: </td>
                             <td>{{ contenido.usuario }}</td>
                        </tr>
                        <tr>
                            <td>numero de comentarios: </td>
                            <td>{{ contenido.NumComent }}</td>
                        </tr>
                      </table>
               </td>
            </tr>
        {%endfor%}
    {%else%}
        <p>Aun no hay contenido a mostrar</p>
    {%endif%}

{% endblock %}
{%block central%}
    {%  if request.user.is_authenticated%}
        <br>
        <p>Introduce contenido nuevo<p>
        <form action="" method ="POST" >
             {% csrf_token %}
           <div id="idformnoticias">
            <table align="left" id="idformnoticias">
               <tr>
                   <td>Titulo:</td>
                   <td><input type="text" class="inputnoticias" name="clave"></td>
               </tr>
                <tr>
                     <td>Cuerpo:</td>
                     <td><input type="text" class="inputnoticias"  name="valor"></td>
                </tr>
            </table>
           </div>
    <input class="boton_personalizado" type="submit" name="action" value="contenido añadido">
        </form>
  {% else %} <br><br>

    <p>Tienes que autenticarte para introducir contenido nuevo</p>
    {%endif%}
{% if request.user.is_authenticated%}
        {%if contenido_list_10_publicaciones%}
<br><br>
             Aportaciones del usuario
             {%for contenido in contenido_list_10_publicaciones%}
<br>
                 {% ifequal contenido.usuario request.user.username %}
                         <a href="{{contenido.clave}}">{{contenido.clave}}</a>
                 {%endifequal%}
            {%endfor%}
             <br>

        {%endif%}
  {%endif%}
<br><br><br><br>

<a href="https://www.urjc.es/contacto">Pagina de Informacion URJC</a></p>
            <iframe src="https://www.urjc.es/contacto" height="400" width="65%" name="demo">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>



{% endblock %}

Proyecto_Final/templates/Cosas Pagina/recurso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <style>
        width: 100%;
        h1{font-size:25px;font-style: oblique;}
        p{font-size:20px;font-style: oblique;}
        body{ background-color: #FBF0FF}

        .header {
          width:98%;
          height:30%;
          overflow: hidden;
          background-color: #C6ACCF;
          padding: 10px 10px;
          border-radius: 10px;
          border-color: #58465F;
          border-style: groove;
          font-size:50px;
          text-align: center;
          font-style: italic;
          color: white;
          margin-left: 1%;

        }
        .session{
           margin-right: 20px;
           width:98%%;
           height:20%;
           overflow: hidden;
           color: white;
           padding: 10px 10px;
           border-radius: 8px;
           border-style: groove;
           background-color: #C6ACCF;
           border-color: #58465F;
           text-align: center;
           font-size:20px;
           padding: 10px;
           margin-left: 1.5%;
           margin-top:5px;
        }
        #session-left{float: left; margin-left: 10%}
        #session-right{float: right; margin-right: 10%}
        #boton_paginappal{justify-content: center;}
        #nombre_usuario{width: 30%; justify-content: center; margin-left: 30%;}
        #idformnoticias{width: 90%;margin-left: 5%; }
        .inputnoticias{width: 100%; }

        main{
            margin-right: 20px;
            width:98%;
            height:20%;
            overflow: hidden;
            color: white;
            padding: 10px 10px;
            border-radius: 8px;
            border-style: groove;
            background-color: #C6ACCF;
            border-color: #58465F;
            margin-top:5px;
            text-align: center;
            font-size:20px;
            margin: 1%;
        }
        aside {
          width: 40%;
          height: 50%;
          text-align: left;
          border: #1245a3 3px solid  ;
          border-radius: 18px;
          padding-top: 20px;
          padding-right: 0px;
          padding-bottom: 40px;
          padding-left: 40px
          margin-right: 20px;
          overflow: auto;
          color: white;
          padding: 10px 10px;
          border-style: groove;
          background-color: #C6ACCF;
          border-color: #58465F;
          margin-top:5px;
          font-size:20px;
          margin-left: 30%;
        }
        .footer{
            clear:both;
            margin: 0px;
            width:100%;
            text-align: right;
            color: black;
            border-style: groove;
            background-color: #C6ACCF;
            border-color: #58465F;
            margin-top:5px;
            font-size:15px;
            height: 10%;
            text-align: center;
        }
        .boton_log{
            text-decoration: none;
            padding: 2px;
            font-weight: 67;
            font-size: 20px;
            background-color: #FBF0FF;
            border-radius: 8px;
            border: black 2px solid ;
            margin:5px;
        }
        .boton_personalizado{
            text-decoration: none;
            padding: 10px;
            font-weight: 600;
            font-size: 17px;
            color: #ffffff;
            background-color: #58465F;
            border-radius: 8px;
            border-style: groove;
            border: #blue 2px solid #;
            width: 50%;
            margin-top: 30px;
        }
        #recurso_boton_borrar_voto{
            text-decoration: none;
            padding: 10px;
            font-weight: 600;
            font-size: 17px;
            color: #ffffff;
            background-color: #58465F;
            border-radius: 8px;
            border-style: groove;
            border: #blue 2px solid #;
            width: 15%;
            margin-top: 10px;
        }
        table{
          font-family: arial, sans-serif;
          border-collapse: collapse;
          width: 300%;
          border: blue 6px solid #;
        }
        td, th {
          border: 2px solid #dddddd;
          text-align: center;
        }

        tablacontent{
         width: 100%;
        }
        img{
        display:block;
        margin:auto;
        }
     </style>
</head>

<{% extends 'Cosas Pagina/schema.html' %}
{%block cuerpo%}


            <tr>
               <td>
                    <table style="width:auto" align="center">
                        <th><a href="/{{contenido.clave}}">{{contenido.clave}}</a></th>
                        <tr>
                            <td>el valor de la clave es:</td>
                            <td>{{ contenido.valor }}</td>
                        </tr>
                        <tr>
                           <td>votos positivos: </td>
                            <td>{{ contenido.nvotos_pos }}</td>
                        </tr>
                        <tr>
                            <td>votos negativos: </td>
                            <td>{{ contenido.nvotos_neg }}</td>
                        </tr>
                        <tr>
                            <td>fecha de publicacion: </td>
                             <td>{{ contenido.fecha }}</td>
                        </tr>
                        <tr>
                            <td>numero de comentarios: </td>
                            <td>{{ contenido.NumComent }}</td>
                        </tr>
                     </table>

               </td>
            </tr>

    {%if request.user.is_authenticated%}
        {%if contenido.voto_set.all%}
            {% for votoaux in contenido.voto_set.all%}
                     {%ifequal votoaux.usuario request.user.username %}
                           <br> Ya ha votado {{votoaux.valor}}
                            <form action="" method ="POST">
                                    {% csrf_token %}
                                 <input class="boton_personalizado" type="submit" name="action" value="borrar voto">
                            </form>
                     {%else%}

                        <br><br>
                        <table style="width:auto" align="center">
                            <form action="" method ="POST">
                                    {% csrf_token %}
                                <input class="boton_personalizado" type="submit" name="action" value="Me gusta">
                            </form>
                            <form action="" method ="POST">
                                    {% csrf_token %}
                                <input class="boton_personalizado" type="submit" name="action" value="No me gusta">
                            </form>
                            </table>
                            <br><br><br>
                     {%endifequal%}
            {%endfor%}
        {%else%}

            <br>
            <table style="width:auto" align="center">
                <form action="" method ="POST">
                        {% csrf_token %}
                    <input class="boton_personalizado" type="submit" name="action" value="Me gusta">
                </form>
                <form action="" method ="POST">
                        {% csrf_token %}
                     <input class="boton_personalizado" type="submit" name="action" value="No me gusta">

                </form>
                </table>

                <br><br>
        {%endif%}
    {%endif%}

<br>

{% block aportacion %}

{% endblock %}

<br><br>
    <p>Comentarios</p>
        {% for comentario in comment_list%}
            <br>
            <table style="width:auto" align="center">
                <tr>
                    <td><b>Titulo:<b/><td>
                    {{comentario.titulo }}
                </tr>
                <tr>
                    <td><b>Valor:<b/><td>
                     {{comentario.valor }}
                </tr>
                <tr>
                    <td><b>Usuario:<b/><td>
                     {{comentario.usuario }}
                </tr>
                <tr>
                    <td><b>Fecha:<b/><td>
                    {{ comentario.fecha }}
                </tr>
                {% if comentario.link_imagen %}
                        <tr>
                            <td><b>La imagen requerida:</b></td>
                            <td><img src="{{comentario.link_imagen}}" align="center" width="200"></td>
                        </tr>
                {% endif %}
            </table>
        {%endfor%}

 <br>
    <p>Votos</p>


        {% for votoaux in contenido.voto_set.all %}

            <table style="width:auto" align="center">
                        <tr>
                               <td><b>usuario:<b/><td>
                               <td>{{votoaux.usuario }}</td>
                        </tr>
                        <tr>
                            <td><b>Valor:<b/><td>
                               <td> {{votoaux.valor }}</td>
                        </tr>
            </table>
        {% endfor %}

<br>

    {% if request.user.is_authenticated %}

                <p>Introduce nuevo comentario</p>
                <form action="" method ="POST">
                    <table style="width:auto" align="center">
                        {% csrf_token %}
                           <tr>
                               <td>Titulo:</td>
                               <td> <input type="text" name="clave"></td>
                            </tr>
                            <tr>
                               <td> <br>Cuerpo:</td>
                               <td> <input type="text" name="valor"></td>
                            </tr>
                        <tr>
                            <td>
                                <br> Link de la imagen:
                            </td>
                            <td>
                                <input type="text" name="link_imagen">
                            </td>
                        </tr>
                    </table>
                        <br/><input class="boton_personalizado"  type="submit" name="action" value="Enviar comentario">
                </form>

    {% else%}

        <p>Para comentar debes iniciar sesion</p>

    {%endif%}
    <br>
        {%ifequal request.user.username contenido.usuario  %}
         <p>Edita el contenido</p>
            <form action="" method ="POST">
                <table style="width:auto" align="center">
                        {% csrf_token %}
                    <tr>
                       <td> Nuevo cuerpo: </td>
                        <td><input type="text" name="valor"></td>
                    </tr>
                </table>
                <br>
                <input class="boton_personalizado" type="submit" name="action" value="Modif. contenido">
            </form>
    <br>
             <p>Borrar contenido</p>
            <form action="" method ="POST">
                    {% csrf_token %}
                <input class="boton_personalizado"type="submit" name="action" value="Borrar contenido">
            </form>

            {%else%}

                <br><p>Solo {{ contenido.usuario }} puede editar esta publicacion</p>

            {%endifequal%}

        <br><br>
         <p>Previsualizacion de <a href={{contenido.valor}}>Pagina recurso</a></p>
       <iframe src="{{ contenido.valor }}" height="400" width="65%" name="demo">
          <p>Navegador no compatible con iframes</p>
        </iframe>
        <br><br>

    <br>
{%endblock%}

Proyecto_Final/templates/Cosas Pagina/recurso_no_recon.html
    <div class="og">
        <p>Titulo</p>
        <img src="https://..../imagen.jpg">
    </div>

    {% extends 'Cosas Pagina/recurso.html' %}
    {%block aportacion%}
        <div class="og">
            <p>Recurso no reconocido en nuestra plataforma, hemos podido extraer esta informacion</p>
            <p>Este es el titulo:{{title}}</p>
            <img src={{img}}>
        </div>

      <a href={{content.valor}}>Artículo
      original</a>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/reddit.html
{% extends 'Cosas Pagina/recurso.html' %}

{%block aportacion%}

    <div class="reddit">
        <p>Subreddit de: {{titulo}}</p>
        <img src="{{ imagen }}" align="center" width="300">

        <p>{{text}}</p>
        <p><a href="https://www.reddit.com/r/django/comments/n842st"> Se ha publicado en [subreddit]</a>.</p>
    </div>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/wikipedia.html
{% extends 'Cosas Pagina/recurso.html' %}

{%block aportacion%}

    <div class="wikipedia">
      <p>Artıculo Wikipedia: {{titulo}}</p>

      <img src={{imagen}}>

      <p>{{text2}}</p>

      <p>Wikipedia es una marca registrada sin animo de lucro de la fundacion Wikipedia Inc.
      <p>Todos los derechos del articulo se asignan a la pagina de wikipedia.

      <a href={{contenido.valor}}>Articulo original de Wikipedia</a>.</p>

    </div>

{%endblock%}

Proyecto_Final/templates/Cosas Pagina/xml.html
<html lang="en">
<head>
    <title>Documento XML</title>
</head>
<body>
    &lt;?xml version="1.0"?>
        <test>

            {% for contenido in Contenido %}

                 <entries>
                    <br><br>&lt;entry id="{{ contenido.id }}">'
                        <br>&lt;clave>{{ contenido.clave }}&lt;/clave>'
                        <br>&lt;valor>{{ contenido.valor }}&lt;/valor:>
                        <br>&lt;usuario>{{ contenido.usuario }}&lt;/usuario>
                        <br>&lt;nvotos_pos>{{ contenido.nvotos_pos }}&lt;/nvotos_pos>
                        <br>&lt;nvotos_neg>{{ contenido.nvotos_neg }}&lt;/nvotos_neg>
                        <br>&lt;fecha>{{ contenido.fecha }}&lt;/fecha>
                 </entries>

            {% endfor %}

        </test>
    </body>
</html>